# Helm Values Specific to Products Microservice
configMapData:
  API_PORT: "31200"
  PORT_SERVER: "8080"

  DATABASE_HOST: products-db
  DATABASE_PORT: "5432"
  DATABASE_NAME: "products-database"
  DATABASE_USER: "postgres"
  DATABASE_DIALECT: "postgres"

secret:
  enabled: true
  data:
    DATABASE_PASSWORD: "TVRJek5EVTI="

# externalServices:
#   - name: products-db
#     externalName: lanchonete-database.ccyadp9cu3n9.us-east-1.rds.amazonaws.com

image:
  repository: "045628470274.dkr.ecr.us-east-1.amazonaws.com/tech-challenge-lanchonete/products"
  tag: "latest"

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

database:
  port: 5432
  exposedPort: 5433
  useStatefulSet: true
  image:
    repository: postgres
    tag: latest
  configMapData:
    POSTGRES_DB: "products-database"
    POSTGRES_USER: "postgres"
    POSTGRES_PORT: "5433"
    VOLUME_DB_DATA: "/var/lib/postgresql/data"
  secretData:
    POSTGRES_PASSWORD: "MTIzNDU2"
