services:
  lanchonete-db-products:
    image: postgres:latest
    container_name: lanchonete_products_postgres
    restart: always
    ports:
      - "${HOST_PORT_DB}:${DATABASE_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db_data:${VOLUME_DB_DATA}
    networks:
      - fiap
    expose:
      - ${DATABASE_PORT}

  lanchonete-products-node:
    build:
      context: .
    container_name: lanchonete-products-node
    depends_on:
      - lanchonete-db-products
    environment:
      PORT_SERVER: ${CONTAINER_PORT_SERVER}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${HOST_PORT_SERVER}:${CONTAINER_PORT_SERVER}"
    restart: always
    networks:
      - fiap
    expose:
      - ${CONTAINER_PORT_SERVER}
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  db_data:

networks:
  fiap:
    driver: bridge
